name: iOS Build Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.0.app

      - name: Install CocoaPods (if needed)
        run: |
          sudo gem install cocoapods
          pod install || echo "No Podfile found"

      - name: Clean and archive app
        run: |
          xcodebuild clean -scheme DexianUserApp -sdk iphoneos -configuration Release
          xcodebuild archive \
            -scheme DexianUserApp \
            -sdk iphoneos \
            -configuration Release \
            -archivePath ${{ github.workspace }}/build/DexianUserApp.xcarchive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath ${{ github.workspace }}/build/DexianUserApp.xcarchive \
            -exportPath ${{ github.workspace }}/build \
            -exportOptionsPlist ExportOptions.plist

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: DexianUserApp.ipa
          path: build/DexianUserApp.ipa

